### ISSUE TITLE
Improve error message for META-INF/services

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/sbt-scalafix#17]
I forgot to add

`rules/src/main/resources/META-INF/services/scalafix.v1.Rule`

It gives me this trace:

```
[info] fix.ScalafixTests *** ABORTED ***
[info]   java.lang.RuntimeException: Failed to load resource scalafix-testkit.properties
[info]   at scala.sys.package$.error(package.scala:27)
[info]   at scalafix.testkit.TestkitProperties$.loadFromResources(TestkitProperties.scala:66)
[info]   at scalafix.testkit.SemanticRuleSuite.<init>(SemanticRuleSuite.scala:23)
[info]   at fix.ScalafixTests.<init>(ScalafixTests.scala:8)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:443)
[info]   ...
```

It should mention what to do (ex what to add and where). Ideally, this could be generated automatically via reflection.

**Comment by olafurpg** [comment]
Did you enable the ScalafixTeskitPlugin? This resource file is
automatically generated by the plugin, see the example-scalafix-rule repo
build.

**Comment by MasseGuillaume** [comment]
Ops, correct, this was due to a missing `.enablePlugins(ScalafixTestkitPlugin)`.

**Comment by olafurpg** [comment]
This is handled by the scalafix.g8 migration rewrite BTW

**Comment by olafurpg** [comment]
testkit does not require services/scalafix.v1.Rule to be provided. The migration path for scalafix.g8 template users will be create a new template and move old rules over so closing as wontfix.
