### ISSUE TITLE
What happened to `scalafixParallel`?

### ISSUE THREAD

**Issue by timcharper** [scalacenter/sbt-scalafix#6]
It is mentioned here:

https://github.com/scalacenter/scalafix/blob/f11dcdf27f5ce1530332e1b8021de0231b0d4dd3/website/src/main/tut/docs/users/faq.md

But it was removed right after moving the source from scalafix to this repo, in this commit:

37ec0c453d86424e645df920fd7cfbc5a629e369

Is this parameter obsolete?

**Comment by olafurpg** [comment]
Thanks for reporting! The setting key has been removed as scalafix no longer runs in parallel. Please stay on v0.5 until there is a stable v0.6 release as the docs are still in flux for the latest changes.
